"""The council-district to community-board crosswalk, generated by `showup crosswalk`.

Committed rather than computed per build for two reasons: the sweep takes ~35 s and the
lines change about once a decade, and a committed crosswalk makes a boundary change a
diff someone reads. `generate`'s `spacing` argument exists for tests.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from .geo import GRID_SPACING_DEG, MIN_SHARE, load_features, overlap_shares
from .model import BOARD_COUNT, DISTRICT_COUNT
from .sources.boards import JOINT_INTEREST_AREAS

__all__ = [
    "CROSSWALK_PATH",
    "CrosswalkError",
    "generate",
    "load",
    "load_boards_to_districts",
    "load_zips",
]

CROSSWALK_PATH = Path("crosswalks/council_to_boards.json")


class CrosswalkError(RuntimeError):
    """The crosswalk is missing, malformed, or does not cover all 51 districts."""


def generate(
    council_geojson: Path,
    community_geojson: Path,
    zip_geojson: Path | None = None,
    *,
    spacing: float = GRID_SPACING_DEG,
) -> dict:
    """Compute the crosswalk. Slow by design; called by `showup crosswalk` only."""
    council = load_features(council_geojson, "coundist")
    if len(council) != DISTRICT_COUNT:
        raise CrosswalkError(f"expected {DISTRICT_COUNT} council districts, found {len(council)}")

    boards = load_features(community_geojson, "boro_cd", exclude=set(JOINT_INTEREST_AREAS))
    if len(boards) != BOARD_COUNT:
        raise CrosswalkError(f"expected {BOARD_COUNT} community districts, found {len(boards)}")

    shares = overlap_shares(council, boards, spacing=spacing)
    # Not a transpose: a share is always of the containing polygon's sampled area, so
    # this answers how much of each board sits in each district.
    reverse = overlap_shares(boards, council, spacing=spacing)

    # The City publishes *modified* ZCTAs, which merge several real ZIPs into one area,
    # so each feature is expanded back out to the codes a person would type.
    zips: dict[str, list[list]] = {}
    if zip_geojson and Path(zip_geojson).exists():
        zctas = load_features(zip_geojson, "modzcta")
        zcta_shares = overlap_shares(zctas, council, spacing=spacing, min_share=0.02)
        members = _zcta_members(zip_geojson)
        for code, pairs in zcta_shares.items():
            if not pairs:
                continue
            for real_zip in members.get(code, [code]):
                zips[real_zip] = [[district, share] for district, share in pairs]

    uncovered = sorted((key for key, value in shares.items() if not value), key=int)
    if uncovered:
        raise CrosswalkError(f"council districts with no community board: {uncovered}")

    return {
        "generated_on": date.today().isoformat(),
        "method": (
            f"lattice sampling at {spacing} degrees (~110 m at the default), "
            f"shares below {MIN_SHARE} dropped as slivers"
        ),
        "sources": {
            "council_districts": "NYC Open Data 872g-cjhh",
            "community_districts": "NYC Open Data 5crt-au7u (joint interest areas excluded)",
        },
        "note": (
            "Shares are approximate and are of sampled land area within the council "
            "district. They may sum to less than 1 where water or unsampled gaps fall "
            "inside the district. Ordering is stable; treat the numbers as indicative."
        ),
        "districts": {
            key: [[code, share] for code, share in value]
            for key, value in sorted(shares.items(), key=lambda kv: int(kv[0]))
        },
        "boards": {
            key: [[code, share] for code, share in value]
            for key, value in sorted(reverse.items(), key=lambda kv: int(kv[0]))
        },
        "zips": dict(sorted(zips.items())),
    }


def _zcta_members(path: Path) -> dict[str, list[str]]:
    """modzcta code -> the real ZIP codes it represents: `10001` is published as a ZCTA
    covering `10001, 10119, 10199`, and a resident types a member, not the code."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    out: dict[str, list[str]] = {}
    for feature in data.get("features", []):
        props = feature.get("properties") or {}
        code = str(props.get("modzcta", "")).strip()
        if not code:
            continue
        raw = str(props.get("zcta") or props.get("label") or code)
        members = [part.strip() for part in raw.split(",") if part.strip().isdigit()]
        out[code] = members or [code]
    return out


def load(path: Path) -> dict[int, list[tuple[str, float]]]:
    """Council district -> its community boards. Validates coverage of all 51."""
    file = Path(path)
    if not file.exists():
        raise CrosswalkError(
            f"{file} is missing. Run `showup crosswalk` to generate it, then commit it."
        )
    data = json.loads(file.read_text(encoding="utf-8"))
    districts = data.get("districts") or {}

    result: dict[int, list[tuple[str, float]]] = {}
    for key, pairs in districts.items():
        result[int(key)] = [(str(code), float(share)) for code, share in pairs]

    missing = [n for n in range(1, DISTRICT_COUNT + 1) if not result.get(n)]
    if missing:
        raise CrosswalkError(f"crosswalk covers no board for council districts {missing}")
    return result


def load_boards_to_districts(path: Path) -> dict[str, list[tuple[int, float]]]:
    """Community district code -> the council districts overlapping it.

    Shares are of the *board's* area, a different number from the district page's, which
    is why the two directions are stored separately rather than transposed.
    """
    file = Path(path)
    if not file.exists():
        raise CrosswalkError(f"{file} is missing. Run `showup crosswalk`.")
    data = json.loads(file.read_text(encoding="utf-8"))
    boards = data.get("boards")
    if not boards:
        raise CrosswalkError(
            f"{file} has no `boards` section — regenerate it with `showup crosswalk`"
        )
    result = {
        str(code): [(int(district), float(share)) for district, share in pairs]
        for code, pairs in boards.items()
    }
    if len(result) != BOARD_COUNT:
        raise CrosswalkError(
            f"crosswalk covers {len(result)} community boards, expected {BOARD_COUNT}"
        )
    empty = sorted(code for code, pairs in result.items() if not pairs)
    if empty:
        raise CrosswalkError(f"community boards with no council district: {empty}")
    return result


def load_zips(path: Path) -> dict[str, list[tuple[int, float]]]:
    """ZIP code -> the council districts it overlaps, largest share first.

    A ZIP routinely straddles two or three, so every overlap is returned and the UI
    offers the choice rather than guessing.
    """
    file = Path(path)
    if not file.exists():
        raise CrosswalkError(f"{file} is missing. Run `showup crosswalk`.")
    data = json.loads(file.read_text(encoding="utf-8"))
    return {
        str(code): [(int(district), float(share)) for district, share in pairs]
        for code, pairs in (data.get("zips") or {}).items()
    }
