// The topic salience index.
//
// THE QUESTION THIS TRIES TO ANSWER
// "Is this topic important or relevant to my community, and is there a lot of
// support, disagreement, or discourse about it?"
//
// WHAT THE CITY ACTUALLY PUBLISHES
// Nothing that measures support, disagreement, or discourse directly. There is
// no public dataset of who testified, what they said, which way they leaned, or
// how many people signed up. Roll-call votes are in Legistar but not in the open
// datasets used here, and the Council's Register to Testify submissions are not
// published as data at all.
//
// So we do not claim to measure sentiment. We measure five things that ARE
// published, keep them separate and visible, and let the reader judge:
//
//   1. localDemand         — how much of your district's casework is this topic
//   2. councilAttention    — how many hearings the relevant committee holds
//   3. legislativeThroughput— how many bills exist, and whether they pass
//   4. localFunding        — Council discretionary dollars in your district
//   5. memberSponsorship   — whether YOUR member sponsors bills on it
//
// The composite `score` is a weighted blend of those five, normalized so the
// strongest topic in a district scores 100. It is a reading aid for ranking a
// long list, not a measurement. Every component is shipped alongside it so the
// number can be taken apart.
//
// SEPARATELY, we compute a citywide per-topic `friction` score. This is the
// closest honest proxy for "contested": bills that get laid over in committee,
// die at end of session, or have to be re-introduced session after session are
// bills that met resistance. It says nothing about which side the resistance
// came from.

export const WEIGHTS = Object.freeze({
  localDemand: 0.4,
  councilAttention: 0.2,
  legislativeThroughput: 0.15,
  localFunding: 0.15,
  memberSponsorship: 0.1,
});

export const WEIGHT_NOTES = Object.freeze({
  localDemand:
    'Share of your district office\'s recorded constituent issues that fall in this topic (2015-2025). Weighted highest because it is the only signal generated by residents of your district.',
  councilAttention:
    'How many hearings the matching committee has held recently, citywide. High attention means frequent, predictable chances to testify.',
  legislativeThroughput:
    'How many bills have been referred to the matching committee, and what share became law. Shows whether hearings here turn into policy.',
  localFunding:
    'Council discretionary dollars awarded to organizations in your district in this topic area. Shows where the Council already spends locally.',
  memberSponsorship:
    'Bills primarily sponsored by the members who have represented your district. Shows what your own representative chooses to champion.',
});

/** Additive smoothing for local shares. */
const SMOOTHING = 25;

const safeDiv = (a, b) => (b ? a / b : 0);
const round = (n, p = 4) => Number(n.toFixed(p));

/**
 * Normalize a map of id -> raw number to id -> 0..1 by dividing by the maximum.
 * Max-normalization (rather than z-scores) keeps the output readable: 1.0 means
 * "the biggest in this group", 0 means "none at all".
 */
function normalizeByMax(entries) {
  const max = Math.max(0, ...entries.map(([, v]) => v));
  return new Map(entries.map(([k, v]) => [k, max > 0 ? v / max : 0]));
}

/**
 * Citywide, per-topic aggregates: attention, throughput, and friction.
 *
 * @param {Map<string, {hearings:number, recentHearings:number}>} hearingsByTopic
 * @param {Map<string, {total:number, enacted:number, filed:number,
 *   laidOver:number, inCommittee:number, reintroduced:number,
 *   daysToEnact:number[]}>} billsByTopic
 */
export function citywideTopicStats(hearingsByTopic, billsByTopic, topicIds) {
  const attention = normalizeByMax(topicIds.map((id) => [id, hearingsByTopic.get(id)?.recentHearings || 0]));
  const throughput = normalizeByMax(topicIds.map((id) => [id, billsByTopic.get(id)?.total || 0]));

  // Friction inputs, each a rate in 0..1 so they are directly comparable.
  const frictionParts = new Map();
  for (const id of topicIds) {
    const b = billsByTopic.get(id);
    if (!b || !b.total) {
      frictionParts.set(id, { stallRate: 0, laidOverRate: 0, reintroRate: 0, n: 0 });
      continue;
    }
    frictionParts.set(id, {
      stallRate: safeDiv(b.filed, b.total),
      laidOverRate: safeDiv(b.laidOver, b.total),
      reintroRate: safeDiv(b.reintroduced, b.total),
      n: b.total,
    });
  }

  const out = new Map();
  for (const id of topicIds) {
    const h = hearingsByTopic.get(id) || { hearings: 0, recentHearings: 0 };
    const b = billsByTopic.get(id) || {
      total: 0,
      enacted: 0,
      filed: 0,
      laidOver: 0,
      inCommittee: 0,
      reintroduced: 0,
      daysToEnact: [],
    };
    const f = frictionParts.get(id);

    const days = [...b.daysToEnact].sort((a, c) => a - c);
    const medianDaysToEnact = days.length ? days[Math.floor(days.length / 2)] : null;

    // Bills with fewer than 15 records give a noisy friction rate; report the
    // count so the UI can suppress the badge rather than us inventing a floor.
    const friction = round((f.stallRate * 0.4 + f.laidOverRate * 0.35 + f.reintroRate * 0.25) * 100, 1);

    out.set(id, {
      topicId: id,
      hearings: h.hearings,
      recentHearings: h.recentHearings,
      hearingsPerYearRecent: h.hearingsPerYearRecent ?? null,
      bills: b.total,
      enacted: b.enacted,
      filedEndOfSession: b.filed,
      laidOverInCommittee: b.laidOver,
      stillInCommittee: b.inCommittee,
      reintroduced: b.reintroduced,
      enactmentRate: b.total ? round(safeDiv(b.enacted, b.total), 3) : null,
      medianDaysToEnact,
      friction,
      frictionParts: {
        stallRate: round(f.stallRate, 3),
        laidOverRate: round(f.laidOverRate, 3),
        reintroRate: round(f.reintroRate, 3),
      },
      frictionSampleSize: f.n,
      attentionNorm: round(attention.get(id) || 0, 3),
      throughputNorm: round(throughput.get(id) || 0, 3),
    });
  }
  return out;
}

/**
 * Per-district, per-topic salience.
 *
 * @param {object} input
 * @param {string[]} input.topicIds
 * @param {Map<string,number>} input.localIssues topicId -> count in this district
 * @param {number} input.localIssueTotal mapped issues in this district
 * @param {Map<string,number>} input.cityIssueShare topicId -> citywide share (0..1)
 * @param {Map<string,number>} input.localFunding topicId -> dollars in this district
 * @param {Map<string,number>} input.sponsorship topicId -> bills sponsored by this district's members
 * @param {Map<string,object>} input.citywide output of citywideTopicStats
 */
export function districtTopicSalience({
  topicIds,
  localIssues,
  localIssueTotal,
  cityIssueShare,
  localFunding,
  sponsorship,
  citywide,
}) {
  // Smoothed local share: a district with 40 total issues should not show a
  // 25% share on the strength of 10 records. Shrink toward the citywide share.
  const smoothedShare = new Map();
  const rawShare = new Map();
  for (const id of topicIds) {
    const n = localIssues.get(id) || 0;
    const prior = cityIssueShare.get(id) || 0;
    rawShare.set(id, safeDiv(n, localIssueTotal));
    smoothedShare.set(id, (n + SMOOTHING * prior) / (localIssueTotal + SMOOTHING));
  }

  const demandNorm = normalizeByMax(topicIds.map((id) => [id, smoothedShare.get(id)]));
  const fundingNorm = normalizeByMax(topicIds.map((id) => [id, localFunding.get(id) || 0]));
  const sponsorNorm = normalizeByMax(topicIds.map((id) => [id, sponsorship.get(id) || 0]));

  const rows = topicIds.map((id) => {
    const city = citywide.get(id) || { attentionNorm: 0, throughputNorm: 0 };
    const components = {
      localDemand: round(demandNorm.get(id) || 0, 3),
      councilAttention: city.attentionNorm || 0,
      legislativeThroughput: city.throughputNorm || 0,
      localFunding: round(fundingNorm.get(id) || 0, 3),
      memberSponsorship: round(sponsorNorm.get(id) || 0, 3),
    };
    const score =
      components.localDemand * WEIGHTS.localDemand +
      components.councilAttention * WEIGHTS.councilAttention +
      components.legislativeThroughput * WEIGHTS.legislativeThroughput +
      components.localFunding * WEIGHTS.localFunding +
      components.memberSponsorship * WEIGHTS.memberSponsorship;

    const cityShare = cityIssueShare.get(id) || 0;
    const local = rawShare.get(id);

    return {
      topicId: id,
      score: round(score * 100, 1),
      components,
      localIssues: localIssues.get(id) || 0,
      localShare: round(local, 4),
      cityShare: round(cityShare, 4),
      // > 1 means residents here raise this more than the citywide average.
      // Computed from the smoothed share so low-volume districts do not produce
      // absurd multiples.
      lift: cityShare > 0 ? round(safeDiv(smoothedShare.get(id), cityShare), 2) : null,
      localFunding: Math.round(localFunding.get(id) || 0),
      sponsoredBills: sponsorship.get(id) || 0,
    };
  });

  // Rescale so the top topic in each district is 100. Without this, districts
  // whose casework is spread thin would look uniformly "unimportant", which is
  // an artifact of normalization rather than a fact about the district.
  const maxScore = Math.max(0, ...rows.map((r) => r.score));
  for (const r of rows) r.score = maxScore > 0 ? round((r.score / maxScore) * 100, 1) : 0;

  return rows.sort((a, b) => b.score - a.score);
}
